[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn horizonh_project_config.wsgi:application"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"