# Generated by Django 5.2.1 on 2025-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True, verbose_name='Room Number')),
                ('room_type', models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('executive', 'Executive Room')], max_length=100, verbose_name='Room Type')),
                ('floor', models.PositiveIntegerField(verbose_name='Floor')),
                ('amenities', models.JSONField(blank=True, default=list, verbose_name='Amenities')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=10, verbose_name='Price')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rooms/', verbose_name='Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['number'],
            },
        ),
    ]
